# Generated by Django 5.0.2 on 2024-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(choices=[('AC', 'Action'), ('CO', 'Comedy'), ('DR', 'Drama'), ('HO', 'Horror'), ('RO', 'Romance'), ('SF', 'Sci-Fi'), ('FA', 'Fantasy'), ('TH', 'Thriller')], default='AC', max_length=100),
        ),
    ]
